module.exports = {
  pro_id: 100007,
  store: 1,
  url: 'https://mpe.hanyu020.com/Api/',
  bar_plugin: {
    "bar_player_strategy": true,
    "bar_recommand": true,
    "bar_membership": true,
    "bar_invite_and_grant": true,
    "bar_deposit": true,
    "bar_one_key_call": true,
    "bar_sales_manager": true,
    "bar_salesman": true,
    "bar_online_mall": true,
    "bar_subsidy": false,
    "bar_online_hall": false,
    "bar_screen": false,
    "bar_driving_service": false,
    "bar_wine_game": false,
    "bar_consult_system": false,
    "bar_order_system": false,
    "bar_check_out_system": false,
    "bar_finance_system": false,
    "bar_admin_system": false,
    "bar_whole_marketing": false,
    "bar_outdoor_marketing": false,
    "bar_persistence_grow": false,
    "bar_purchase_system": false,
    "bar_entertain_ecology": false
  }
}